### ISSUE TITLE
Upgrade AppData\Roaming\npm

### ISSUE THREAD

**Issue by BarryThePenguin** [felixrieseberg/npm-windows-upgrade#3]
I can only find reference to the npm install in ProgramFiles, I didn't see a reference to $env:APPDATA

I haven't spent much time looking at how the script works, but can it upgrade npm installs in AppData\Roaming\npm too? I noticed the npm [documentation](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) references this tool but there's no mention to dealing with AppData installs

**Comment by felixrieseberg** [comment]
Hey, if you didn't attempt to install npm with `npm install -g npm`, everything is fine. Even if you did, things are still okay - Windows will however use the npm installed with Node.js instead, since the official Node.js installer references the Node directory in `PATH` before the global AppData directory.

This installer is trying to minimally invasive and upgrade the npm version inside the Node.js folder (which should be the one installed used anyway, unless the user provisioned npm or node him/herself.)

*If* Windows is already using the one in `%appdata%\npm\node_modules\npm`, the installer is actually not required - and a simple `npm install -g npm@latest` is enough to upgrade.

Does that make sense? Or did I misunderstand you?

**Comment by BarryThePenguin** [comment]
I have used `npm install -g npm`, the main issue with this method is the npmrc file gets removed during the install. This breaks npm until you replace the npmrc file.

If this tool was only meant to upgrade npm in the Node.js folder *and* `nodejs\node_modules\npm` is the npm instance we *should* be using, I'm happy with that as the solution :+1:

**Comment by felixrieseberg** [comment]
Good point. I don't want to put myself or Microsoft into the position of telling people how to use npm. I can probably get the path of the `npm` installation used and update that one.

**Comment by mahlu** [comment]
getting the below error

$ npm install -g npm-windows-upgrade
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Mahlu\\AppData\\
Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm-windows-up
grade"
npm ERR! node v0.12.3
npm ERR! npm  v2.12.0

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Mahlu\Desktop\npm-debug.log


0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Users\\Mahlu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm-windows-upgrade' ]
2 info using npm@2.12.0
3 info using node@v0.12.3
4 verbose install initial load of C:\Users\Mahlu\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Mahlu\AppData\Roaming\npm\package.json
6 silly cache add args [ 'npm-windows-upgrade', null ]
7 verbose cache add spec npm-windows-upgrade
8 silly cache add parsed spec { raw: 'npm-windows-upgrade',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: 'npm-windows-upgrade',
8 silly cache add   spec: 'c:\\Users\\Mahlu\\Desktop\\npm-windows-upgrade',
8 silly cache add   type: 'local' }
9 silly addLocalTarball shasum (computed) 3ab1fde9232a4bc9b623210106df95a4e1c0939d
10 verbose addTmpTarball c:\Users\Mahlu\Desktop\npm-windows-upgrade not in flight; adding
11 verbose stack TypeError: undefined is not a function
11 verbose stack     at calculateOwner (c:\Users\Mahlu\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
11 verbose stack     at c:\Users\Mahlu\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
11 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
12 verbose cwd c:\Users\Mahlu\Desktop
13 error Windows_NT 6.1.7601
14 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Mahlu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm-windows-upgrade"
15 error node v0.12.3
16 error npm  v2.12.0
17 error undefined is not a function
18 error If you need help, you may report this error at:
18 error     <https://github.com/npm/npm/issues>
19 verbose exit [ 1, true ]

**Comment by cchamberlain** [comment]
If I am understanding everything correct, I believe the [pull request](https://github.com/felixrieseberg/npm-windows-upgrade/pull/8) I sent that was integrated should be causing the default behavior now to first query the first npm in your path for its global install location via -
`npm config --global get prefix`

I'd expect this to return the `AppData` path if that's the install you have, although my current setup is installed at another location within my home directory so I can't test that assumption very well at the moment.  Perhaps this issue is fixed?

**Comment by felixrieseberg** [comment]
I assume this issue is fixed no - if we fail with installing npm in AppData, we're now _also_ installing the desired version in the NodeJS folder. I'll close this as fixed.

Thanks everybody!
