### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by zckrs** [felixrieseberg/npm-windows-upgrade#30]
A issue a little surprising to thank you for that complete and efficient script. 

Thou hast taken away pain.

![](http://i.giphy.com/nU704Y2jeFOHm.gif)

**Comment by alopes** [comment]
+1

**Comment by jaylinski** [comment]
:+1:

**Comment by fgilio** [comment]
:+1:

**Comment by jan-dh** [comment]
+1

**Comment by Zmoki** [comment]
+1

**Comment by Akamaozu** [comment]
:+1: 

My electron app couldn't be built on my Windows machine due to excessively long path names. 

npm3's dependency graph means shorter paths, which meant I didn't need to jump through the hoops I was to get things working correctly. 

Thanks for making this package that made it possible to upgrade trivially :)

**Comment by grzesiekrzaca** [comment]
:clap:

**Comment by docrinehart** [comment]
:+1: :boom: :+1:

**Comment by liuxiaojiu** [comment]
+1 Thanks!

**Comment by HubleGiter** [comment]
+++
