### ISSUE TITLE
If your domain policy has script executionPolicy set to remoteSigned, how can you use npm-windows-upgrade?

### ISSUE THREAD

**Issue by mcking65** [felixrieseberg/npm-windows-upgrade#88]
PS C:\users\mck> get-executionPolicy -list

```
    Scope ExecutionPolicy
    ----- ---------------
```

MachinePolicy    RemoteSigned
   UserPolicy    RemoteSigned
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine       Undefined
I have used gpedit.msc to edit local policy so this is coming from my company's domain.

Does this mean it is not possible to use npm-windows-upgrade?

**Comment by skyguy94** [comment]
Did you try setting it as the instructions indicated? It should work fine.

Installing into Program Files requires Administrator permissions and the script checks for that. If you have Administrator permissions you can also override the default execution policy. Their instructions on setting the `ExecutionPolicy` to `Unrestricted` makes use of that fact.

It would be wiser if the script just used `-Bypass` since it already knows it has administrator permissions and they could remove the `Set-ExecutionPolicy` instructions altogether.

Caveat, I don't know how this works with GPO/domains, so I'm interested in your efforts if you do try it.

**Comment by alexxgathp** [comment]
In addition to the above, I was also getting an error message when trying to set the permissions with Set-ExecutionPolicy.
I ended up giving up on it and installing manually, since I don't use PowerShell much yet and usually not on that particular Windows 7 environment.
```
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
execution policy of RemoteSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
information please see "Get-Help Set-ExecutionPolicy".At line:1 char:1
+ Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
```

**Comment by mcking65** [comment]
I raised the issue because I was getting the same errors as @alexxgathp. Sorry, I should have included that output. There is no way to override the machine policy that is set by a domain administrator.

**Comment by felixrieseberg** [comment]
Hey everyone! I just added a code signature to the PowerShell parts of `npm-windows-upgrade` - would one of you do me a favor and give a quick try? I'd really appreciate it!

**Comment by bdukes** [comment]
@felixrieseberg, the powershell execution policy check is still happening, so you need to call it with the `--no-execution-policy-check` flag, but then it worked fine for me.

That policy check should probably just fail for `Restricted`, rather than looking for `Unrestricted`.  Now that the script it signed, that should be the only policy that would have an issue.  Alternatively, as @skyguy94 mentioned, you might as well just start `powershell` with `Bypass

**Comment by franklinyu** [comment]
Not sure if this helps, but I updated npm with `RemoteSigned` permission even without the `--no-execution-policy-check` flag. Thanks for signing the PowerShell script!
